plugins:
  - jekyll-archives
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

permalink: pretty
baseurl: "/"
url: "https://andrwcnln.github.io"

author: Andrew Conlin
    
defaults:
  # blog
  - scope:
      path: "_posts/blog"
      type: posts
    values:
      permalink: blog/:year/:month/:day/:title/
      layout: post
  # til
  - scope:
      path: "_posts/til"
      type: posts
    values:
      permalink: til/:title/
      category: til
      layout: post

feed:
  categories: 
    - blog
    - til